version: "3.8"

services:
  # Banco de Dados
  database:
    image: mysql:latest
    container_name: mysql-database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql

  # Fila
  queue:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
